plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.sherlockbui.beautycamera'
version = '0.2.3'

android {
  namespace 'expo.modules.beautycamera'

  defaultConfig {
    minSdkVersion 26
    versionCode 3
    versionName '0.2.3'
  }
}

dependencies {
  def cameraxVersion = '1.5.1'
  implementation "androidx.camera:camera-core:${cameraxVersion}"
  implementation "androidx.camera:camera-camera2:${cameraxVersion}"
  implementation "androidx.camera:camera-lifecycle:${cameraxVersion}"
  implementation "androidx.camera:camera-view:${cameraxVersion}"
  implementation 'com.google.mlkit:face-detection:16.1.7'
  implementation('com.google.mediapipe:tasks-vision:0.10.14') {
    exclude group: 'com.google.auto.value', module: 'auto-value'
  }
}
